CREATE TABLE persons (
  uuid BINARY(32) NOT NULL PRIMARY KEY,
  login VARCHAR(200) NOT NULL,
  password VARCHAR(200) NOT NULL,
  first_name VARCHAR(200) NOT NULL,
  last_name VARCHAR(200) NOT NULL,
  username VARCHAR(200) NOT NULL,
  birth_date TIMESTAMP NOT NULL,
  telephone_number VARCHAR(200) NOT NULL,
  mail_address VARCHAR(200) NOT NULL
);

CREATE UNIQUE INDEX ix_unique_telephone_number_persons ON persons(telephone_number);
CREATE UNIQUE INDEX ix_unique_username_persons ON persons(username);

CREATE TABLE teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL PRIMARY KEY,
  name VARCHAR(200) NOT NULL
);

CREATE UNIQUE INDEX ix_unique_name_teams ON teams(name);

CREATE TABLE workers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL PRIMARY KEY,
  person_id BINARY(32) NOT NULL,
  team_id BIGINT NOT NULL,
  person_role VARCHAR(200) NOT NULL,
  foreign key (person_id) references persons(uuid),
  foreign key (team_id) references teams(id)
);

CREATE UNIQUE INDEX ix_unique_worker ON workers(person_id, team_id, person_role);

CREATE TABLE tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL PRIMARY KEY,
  code VARCHAR(200) NOT NULL,
  title VARCHAR(200) NOT NULL,
  description VARCHAR(200) NULL,
  author_id BIGINT NULL,
  status VARCHAR(200) NOT NULL DEFAULT 'open',
  priority VARCHAR(200) NOT NULL DEFAULT 'medium',
  estimate INT NULL,
  foreign key (author_id) references workers(id)
);

CREATE UNIQUE INDEX ix_unique_code_tasks ON tasks(code);

CREATE TABLE worker_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL PRIMARY KEY,
  worker_id BIGINT NOT NULL,
  task_id BIGINT NOT NULL,
  worker_role VARCHAR(200) NOT NULL, --executors observers author
  foreign key (worker_id) references workers(id),
  foreign key (task_id) references tasks(id)
);

CREATE UNIQUE INDEX ix_unique_worker_tasks ON worker_tasks(worker_id, task_id);
